disabled_rules:
  - trailing_whitespace
excluded:
  - Carthage
  - Pods
  - vendor
  - DemoTests
  - DemoUITests
  - Demo/Resources/SwiftGen
type_name:
  excluded:
    - T
line_length:
  ignores_comments: true
identifier_name:
  excluded:
    - pi
    - x
    - y
    - id
    - ex
    - ok

